### ISSUE TITLE
add handler for crashed pages

### ISSUE THREAD

**Issue by trodevel** [trodevel/twitch_tool#42]
```
DEBUG: waiting till loaded .Traceback (most recent call last):
  File "follower.py", line 455, in <module>
    main( sys.argv[1:] )
  File "follower.py", line 450, in main
    process( user_file, status_filename, mode, is_headless )
  File "follower.py", line 388, in process
    process_users( driver, status, status_filename, users, mode )
  File "follower.py", line 303, in process_users
    is_succeded, follow_type = follow_user( driver, u )
  File "follower.py", line 195, in follow_user
    return follow_user_core( driver, username )
  File "follower.py", line 166, in follow_user_core
    b1 = detect_follow_unfollow_button( driver )
  File "follower.py", line 95, in detect_follow_unfollow_button
    b1 = has_follow_button( driver )
  File "follower.py", line 77, in has_follow_button
    return has_follow_or_unfollow_button( driver, False )
  File "follower.py", line 71, in has_follow_or_unfollow_button
    return helpers.does_xpath_exist_with_timeout( driver, path, 10 )
  File "/home/apps/tools/scraping_helpers/helpers.py", line 128, in does_xpath_exist_with_timeout
    res = does_xpath_exist( parent, name )
  File "/home/apps/tools/scraping_helpers/helpers.py", line 115, in does_xpath_exist
    elems = parent.find_elements_by_xpath( name )
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 410, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 1007, in find_elements
    'value': value})['value'] or []
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=89.0.4389.90)


```

**Comment by trodevel** [comment]
https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot

Solution

There are diverse solution to this issue. However as per UnknownError: session deleted because of page crash from tab crashed this issue can be solved by either of the following solutions:

    Add the following chrome_options:

    chrome_options.add_argument('--no-sandbox')         

    Chrome seem to crash in Docker containers on certain pages due to too small /dev/shm. So you may have to fix the small /dev/shm size.

    An example:

    sudo mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=512M tmpfs /dev/shm

    It also works if you use -v /dev/shm:/dev/shm option to share host /dev/shm

    Another way to make it work would be to add the chrome_options as --disable-dev-shm-usage. This will force Chrome to use the /tmp directory instead. This may slow down the execution though since disk will be used instead of memory.

    chrome_options.add_argument('--disable-dev-shm-usage')

**Comment by trodevel** [comment]
- simple continuation after page crash will not help
- it looks like it is necessary to re-initialize the driver

```
INFO: followed user 8 / 5031 - xxxxxxxxxxx
INFO: saved 174 records to user/status.csv
INFO: following user 9 / 5031 - xxxxxxxxxxx
DEBUG: waiting till loaded .ERROR: page crashed
ERROR: failed to follow user 9 / 5031 - xxxxxxxxxxx
INFO: following user 10 / 5031 - xxxxxxxxxxx
ERROR: page crashed

```
